### PR TITLE
Removed remoting context

### LINKED ISSUE #16: Getting remoting.context option was removed in version 3.0 error
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Affected example version: 3.0

Steps:

```
$ git clone https://github.com/strongloop/loopback-example-storage.git
$ cd loopback-example-storage/example-3.0
$ npm install
$ node .
```

### Link to sample repo to reproduce issue (if bug)

https://github.com/strongloop/loopback-example-storage/tree/master/example-3.0

### Expected result

Project should start the server and file uploads should work properly.

### Actual result (if bug)

```

D:\test\loopback-example-storage\example-3.0>node .
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
Unhandled error for request GET /api/containers/container1/files: Error: remoting.context option was removed in version 3.0. See http://loopback.io/doc/en/lb2/Using-current-context.html for more details.
    at restApiHandler (D:\test\loopback-example-storage\example-3.0\node_modules\loopback\server\middleware\rest.js:45:15)
    at Layer.handle [as handle_request] (D:\test\loopback-example-storage\example-3.0\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\test\loopback-example-storage\example-3.0\node_modules\express\lib\router\index.js:312:13)
    at D:\test\loopback-example-storage\example-3.0\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (D:\test\loopback-example-storage\example-3.0\node_modules\express\lib\router\index.js:330:12)
    at next (D:\test\loopback-example-storage\example-3.0\node_modules\express\lib\router\index.js:271:10)
    at cors (D:\test\loopback-example-storage\example-3.0\node_modules\cors\lib\index.js:179:7)
    at D:\test\loopback-example-storage\example-3.0\node_modules\cors\lib\index.js:229:17
    at originCallback (D:\test\loopback-example-storage\example-3.0\node_modules\cors\lib\index.js:218:15)
    at D:\test\loopback-example-storage\example-3.0\node_modules\cors\lib\index.js:223:13
    at optionsCallback (D:\test\loopback-example-storage\example-3.0\node_modules\cors\lib\index.js:204:9)
    at corsMiddleware (D:\test\loopback-example-storage\example-3.0\node_modules\cors\lib\index.js:209:7)
    at Layer.handle [as handle_request] (D:\test\loopback-example-storage\example-3.0\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\test\loopback-example-storage\example-3.0\node_modules\express\lib\router\index.js:312:13)
    at D:\test\loopback-example-storage\example-3.0\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (D:\test\loopback-example-storage\example-3.0\node_modules\express\lib\router\index.js:330:12)

```

### Additional information (Node.js version, LoopBack version, etc)

Node: 6.9.5
Loopback: 3

### PR DESCRIPTION
**Pull request by rehrumesh**
### Description

Fixed #16 by removeing `context` from remoting object.

#### Related issues

- #16

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by rehrumesh** [comment]
@superkhau can you review this please?

**Review by b-admike — APPROVED** [review]

**Comment by b-admike** [comment]
@rehrumesh Thank you for the patch! @slnode test please

**Comment by b-admike** [comment]
Please rebase your branch, and we should be able to land!

**Comment by rehrumesh** [comment]
@b-admike, I have updated the branch.

**Pull request merged**
